USE [StoriesByUs]
GO

SET IDENTITY_INSERT [UserType] ON
INSERT INTO [UserType] ([ID], [Name]) VALUES (1, 'Admin'), (2, 'ReaderAuthor');
SET IDENTITY_INSERT [UserType] OFF

SET IDENTITY_INSERT [User] ON
INSERT INTO [User] (
	[Id], [FirebaseUserId], [DisplayName], [Email], [UserTypeId], [Bio])
VALUES (1, '13hHvMXBWWZ8eyoKNUfaLbZyoK43', 'sorac', 'sora@place.com', 1, 'I love my pets'),
       (2, '4qCXJ35Bpvfl6JoyE4sPCIaIfbf1', 'freds', 'fred@place.com', 2, 'I am super duper lame'),
       (3, 'e2gN7h3oVXdTef3c1o5mvLl8Rsk2', 'jasminep', 'jasmine@place.com', 2, 'I am pretty awesome');
SET IDENTITY_INSERT [User] OFF

SET IDENTITY_INSERT [Genre] ON
INSERT INTO [Genre] ([Id], [Name]) 
VALUES (1, 'Drama'), (2, 'Comedy'), (3, 'Adventure'), (4, 'Friendship'), (5, 'Tragedy'), 
	   (6, 'Horror'), (7, 'Mystery/Crime'), (8, 'Fantasy'), (9, 'Science Fiction'), 
	   (10, 'Romance'), (11, 'Thriller'), (12, 'Historical'), (13, 'Western'), (14, 'Dystonian'), (15, 'Action/Adventure'), 
	   (16, 'Coming of Age'), (17, 'Fairytale'), (18, 'Poetry'), (19, 'Political'), 
	   (20, 'Satire'), (21, 'Suspense'), (22, 'Young Adult'), (23, 'Mythology/Folklore'), (24, 'Parody/Satire');
SET IDENTITY_INSERT [Genre] OFF

SET IDENTITY_INSERT [Tag] ON
INSERT INTO [Tag] ([Id], [Name])
VALUES (1, 'Time Travel'), (2, 'Unrequited Love'), (3, 'Fluff'), (4, 'Violence'), (5, 'Angst'), (6, 'War'), (7, 'Friends to Lovers'), (8, 'Roommates'), (9, 'Espionage'), (10, 'Tea'), (11, 'Government'), (12, 'Magic'), (13, 'Swearing'), (14, 'Secrets'), (15, 'Slow Burn'), (16, 'Hospital'), (17, 'School'), (18, 'Crack'), (19, 'Crack Treated Seriously'), (20, 'Time Loop'), (21, 'Space'), (22, 'Medieval'), (23, 'Reincarnation'), (24, 'Soulmates'), (25, 'Illness'), (26, 'Snakes'), (27, 'Moral Dilemmas'), (28, 'Betrayal'), (29, 'Enemies to Friends'), (30, 'Enemies to Lovers'), (31, 'Grief/Mourning'), (32, 'Suicide'), (33, 'Death'), (34, 'Hurt/Comfort'), (35, 'Epic'), (36, 'Happy Ending'), (37, 'Jealousy'), (38, 'Falling in Love'), (39, 'Alcohol Use'), (40, 'Drug Use'), (41, 'Science'), (42, 'Aftermath'), (43, 'Dimension Travel'), (44, 'First Time'), (45, 'Demons'), (46, 'Supernatural Elements'), (47, 'Orphans'), (48, 'No Romance'), (49, 'Cats'), (50, 'Self-Indulgent'), (51, 'Alternate Universe'), (52, 'Abuse'), (53, 'Established Relations'), (54, 'Found Family'), (55, 'Protective'), (56, 'Hate'), (57, 'Tense'), (58, 'Nerdy'), (59, 'Geeky'), (60, 'Cute'), (61, 'Insanity'), (62, 'Oneshot'), (63, 'Drabbles'), (64, 'Collection'), (65, 'Love at First Sight'), (66, 'Long'), (67, 'Strong Femal Characters'), (68, 'Female Friendship'), (69, 'Male Friendship'), (70, 'Male-Female Friendship'), (71, 'Male-Male Pairing'), (72, 'Female-Female Pairing'), (73, 'Male-Female Pairing'), (74, 'Confessions'), (75, 'Kids'), (76, 'Developing Friendships'), (77, 'Age Regresssion'), (78, 'Politics'), (79, 'Telepathy'), (80, 'Geniuses'), (81, 'Transgender Themes'), (82, 'Queer'), (83, 'Superpowers'), (84, 'Childhood'), (85, 'Body Switch'), (86, 'Ninjas'), (87, 'Cheesy'), (88, 'Trauma'), (89, 'Unresolved Sexual Tension'), (90, 'Religion'), (91, 'Queerplatonic Relationships'), (92, 'Platonic Relationships'), (93, 'PTSD'), (94, 'Dysfunctional Family'), (95, 'Misunderstandings'), (96, 'Meta'), (97, 'Whump'), (98, 'Pizza'), (99, 'First Meetings'), (100, 'Cooking');
SET IDENTITY_INSERT [Tag] OFF

SET IDENTITY_INSERT [Rating] ON
INSERT INTO [Rating] ([Id], [Level])
VALUES (1, 'G'), (2, 'PG'), (3, 'PG-13'), (4, 'R'), (5, 'NC-17');
SET IDENTITY_INSERT [Rating] OFF

SET IDENTITY_INSERT [Story] ON
INSERT INTO [Story] (
	[Id], [Title], [Summary], [Notes], [PublishedDateTime], [LastUpdatedDateTime], [RatingId], [UserId], [Complete])
VALUES (1, 'Lorem ipsum', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Facilisi etiam dignissim diam quis enim lobortis. Purus gravida quis blandit turpis cursus. Proin libero nunc consequat interdum varius sit. Fringilla ut morbi tincidunt augue interdum velit euismod in. Ultrices in iaculis nunc sed augue lacus viverra.', NULL, 1/19/2020, 1/19/2020, 1, 1, 0);
SET IDENTITY_INSERT [Story] OFF

SET IDENTITY_INSERT [Chapter] ON
INSERT INTO [Chapter] (
	[Id], [Title], [Body], [PlaceInOrder], [Notes], [StoryId])
VALUES (1, 'Viverra vitae', '<p>In nisl nisi scelerisque eu ultrices vitae auctor eu augue. Aliquam sem et tortor consequat id porta nibh venenatis. In aliquam sem fringilla ut morbi. Quam id leo in vitae turpis massa. Elementum integer enim neque volutpat ac tincidunt vitae semper quis. Vestibulum rhoncus est pellentesque elit. Turpis in eu mi bibendum neque egestas congue quisque. In hendrerit gravida rutrum quisque non tellus orci. Nisi quis eleifend quam adipiscing vitae proin sagittis. Cursus mattis molestie a iaculis at erat. Faucibus nisl tincidunt eget nullam non nisi est sit amet. Scelerisque eu ultrices vitae auctor eu augue. Congue nisi vitae suscipit tellus mauris. Diam maecenas sed enim ut. Condimentum vitae sapien pellentesque habitant morbi. Eros in cursus turpis massa tincidunt dui. Molestie ac feugiat sed lectus. Eget lorem dolor sed viverra ipsum. Semper viverra nam libero justo.</p>

<p>Pulvinar proin gravida hendrerit lectus. Sed elementum tempus egestas sed sed risus. Gravida arcu ac tortor dignissim convallis aenean. Enim lobortis scelerisque fermentum dui faucibus. Fermentum dui faucibus in ornare quam viverra orci sagittis eu. Est ultricies integer quis auctor elit. Blandit turpis cursus in hac habitasse platea dictumst quisque. Sapien eget mi proin sed libero. Purus viverra accumsan in nisl. At urna condimentum mattis pellentesque id nibh tortor. Dictum varius duis at consectetur lorem donec massa sapien. Sed augue lacus viverra vitae. Senectus et netus et malesuada fames ac turpis egestas. Consectetur purus ut faucibus pulvinar elementum integer enim neque volutpat. Arcu vitae elementum curabitur vitae nunc sed. Sit amet purus gravida quis blandit turpis cursus. Risus ultricies tristique nulla aliquet enim tortor at auctor urna. Montes nascetur ridiculus mus mauris vitae ultricies leo.</p>

<p>Amet risus nullam eget felis eget nunc lobortis mattis aliquam. Vulputate enim nulla aliquet porttitor lacus luctus. Lacus vestibulum sed arcu non. Faucibus scelerisque eleifend donec pretium vulputate sapien nec. Facilisis mauris sit amet massa vitae tortor condimentum lacinia quis. Feugiat nisl pretium fusce id velit ut. Odio tempor orci dapibus ultrices in iaculis. Volutpat diam ut venenatis tellus. Ut etiam sit amet nisl purus in mollis. Nulla facilisi nullam vehicula ipsum a arcu cursus vitae. Maecenas pharetra convallis posuere morbi leo urna molestie. Nullam vehicula ipsum a arcu. Vivamus arcu felis bibendum ut tristique et egestas quis. Praesent semper feugiat nibh sed pulvinar. Pulvinar elementum integer enim neque volutpat ac tincidunt vitae. Neque volutpat ac tincidunt vitae semper quis lectus nulla.</p>

<p>Mattis nunc sed blandit libero volutpat sed cras ornare. Nisl suscipit adipiscing bibendum est ultricies integer quis auctor elit. Orci porta non pulvinar neque. Eu turpis egestas pretium aenean pharetra magna ac placerat vestibulum. Auctor neque vitae tempus quam pellentesque nec nam. Nibh sed pulvinar proin gravida hendrerit lectus. Vulputate ut pharetra sit amet aliquam id diam maecenas ultricies. Egestas fringilla phasellus faucibus scelerisque eleifend donec pretium vulputate sapien. Sed risus ultricies tristique nulla aliquet enim tortor. Cursus risus at ultrices mi tempus imperdiet nulla malesuada. Ut diam quam nulla porttitor massa id neque. Turpis egestas integer eget aliquet. Sagittis eu volutpat odio facilisis mauris sit amet. Purus ut faucibus pulvinar elementum integer enim.</p>

<p>Nec feugiat in fermentum posuere urna nec tincidunt. Porttitor massa id neque aliquam vestibulum. Consectetur adipiscing elit duis tristique sollicitudin. Eu nisl nunc mi ipsum faucibus vitae. Odio ut sem nulla pharetra diam. Mattis nunc sed blandit libero volutpat sed cras ornare. Venenatis a condimentum vitae sapien pellentesque habitant morbi. Sapien eget mi proin sed libero. Semper viverra nam libero justo. Eleifend quam adipiscing vitae proin sagittis nisl rhoncus mattis.</p>

<p>Volutpat lacus laoreet non curabitur gravida arcu ac. Pharetra vel turpis nunc eget lorem dolor sed viverra ipsum. Sit amet commodo nulla facilisi nullam vehicula ipsum a arcu. Id eu nisl nunc mi ipsum faucibus vitae aliquet. Nullam eget felis eget nunc lobortis mattis aliquam faucibus. Ultricies leo integer malesuada nunc. Convallis posuere morbi leo urna molestie at. Viverra aliquet eget sit amet tellus. Molestie at elementum eu facilisis sed odio morbi quis commodo. Proin sed libero enim sed faucibus turpis. Vitae sapien pellentesque habitant morbi tristique senectus. Volutpat consequat mauris nunc congue nisi. Ante metus dictum at tempor. Nam at lectus urna duis convallis convallis. Ut venenatis tellus in metus vulputate eu. Vivamus arcu felis bibendum ut tristique et. Egestas purus viverra accumsan in.</p>

<p>Auctor eu augue ut lectus arcu. Eget nullam non nisi est sit. Consectetur adipiscing elit duis tristique sollicitudin nibh sit amet commodo. Tortor consequat id porta nibh. In mollis nunc sed id semper risus in hendrerit gravida. Quam elementum pulvinar etiam non. Ut sem viverra aliquet eget sit amet tellus cras adipiscing. Nunc id cursus metus aliquam eleifend mi. Ullamcorper dignissim cras tincidunt lobortis feugiat vivamus at. Viverra tellus in hac habitasse platea dictumst vestibulum. Id aliquet lectus proin nibh nisl condimentum id. Tempor nec feugiat nisl pretium fusce id velit ut tortor. Nulla facilisi etiam dignissim diam quis enim lobortis scelerisque. Vitae congue eu consequat ac felis donec. Blandit cursus risus at ultrices mi tempus imperdiet nulla malesuada. Risus nec feugiat in fermentum posuere urna. Tempus quam pellentesque nec nam aliquam sem et tortor consequat. Consectetur adipiscing elit ut aliquam purus sit amet luctus.</p>

<p>Eget nunc scelerisque viverra mauris in aliquam sem fringilla ut. Tincidunt id aliquet risus feugiat. Vitae justo eget magna fermentum iaculis eu non diam. Lectus arcu bibendum at varius. Nulla posuere sollicitudin aliquam ultrices sagittis orci a scelerisque. Turpis cursus in hac habitasse platea dictumst quisque. Nisl purus in mollis nunc sed id. Dolor sit amet consectetur adipiscing elit duis tristique sollicitudin. At imperdiet dui accumsan sit amet. Nulla at volutpat diam ut venenatis tellus. Nec sagittis aliquam malesuada bibendum arcu. Nibh nisl condimentum id venenatis a. Commodo sed egestas egestas fringilla phasellus faucibus scelerisque eleifend. Et malesuada fames ac turpis egestas. Tincidunt nunc pulvinar sapien et ligula ullamcorper malesuada proin libero. Eget aliquet nibh praesent tristique magna sit amet. Habitasse platea dictumst vestibulum rhoncus est. Suspendisse interdum consectetur libero id faucibus nisl tincidunt.</p>

<p>Leo integer malesuada nunc vel risus commodo. Quisque id diam vel quam elementum pulvinar etiam. Sit amet mauris commodo quis. Dui sapien eget mi proin sed libero enim sed faucibus. Enim ut sem viverra aliquet eget sit amet tellus cras. Tristique senectus et netus et malesuada fames ac turpis egestas. Fusce ut placerat orci nulla pellentesque. Est ullamcorper eget nulla facilisi etiam dignissim diam. Lacus vestibulum sed arcu non odio. Nullam vehicula ipsum a arcu cursus. Cras tincidunt lobortis feugiat vivamus at augue eget. Vel orci porta non pulvinar neque laoreet suspendisse interdum. Dolor sed viverra ipsum nunc. Iaculis at erat pellentesque adipiscing commodo elit at imperdiet dui. Risus at ultrices mi tempus imperdiet.</p>', 1, NULL, 1), (2, 'Sit amet', '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Laoreet non curabitur gravida arcu ac. Feugiat in ante metus dictum at. Rhoncus est pellentesque elit ullamcorper. Molestie nunc non blandit massa enim nec dui. Amet consectetur adipiscing elit ut aliquam purus sit amet luctus. Dignissim cras tincidunt lobortis feugiat vivamus at. Id aliquet lectus proin nibh nisl condimentum id venenatis a. Risus quis varius quam quisque id diam. Turpis in eu mi bibendum neque egestas congue quisque. Nibh nisl condimentum id venenatis. Tempus imperdiet nulla malesuada pellentesque elit. Non blandit massa enim nec.</p>

<p>Elit scelerisque mauris pellentesque pulvinar pellentesque habitant morbi tristique. Integer malesuada nunc vel risus commodo viverra maecenas accumsan. Phasellus faucibus scelerisque eleifend donec pretium vulputate sapien. Suspendisse potenti nullam ac tortor vitae. Tristique senectus et netus et malesuada. Etiam dignissim diam quis enim lobortis scelerisque fermentum. Dictum sit amet justo donec enim diam vulputate ut pharetra. Ornare aenean euismod elementum nisi quis eleifend quam adipiscing vitae. Ut tortor pretium viverra suspendisse potenti nullam. Commodo viverra maecenas accumsan lacus vel facilisis volutpat. Nunc consequat interdum varius sit amet mattis vulputate enim. Urna duis convallis convallis tellus id.</p>

<p>Sit amet venenatis urna cursus eget nunc scelerisque. Tortor dignissim convallis aenean et tortor at risus viverra. Adipiscing enim eu turpis egestas pretium aenean pharetra magna ac. At auctor urna nunc id cursus metus. Ullamcorper eget nulla facilisi etiam dignissim diam quis enim lobortis. Lacus sed turpis tincidunt id aliquet risus. Id donec ultrices tincidunt arcu non. In aliquam sem fringilla ut morbi tincidunt augue. Odio eu feugiat pretium nibh ipsum consequat nisl vel. Aliquam etiam erat velit scelerisque in dictum non consectetur. Mattis ullamcorper velit sed ullamcorper morbi. Volutpat sed cras ornare arcu.</p>

<p>Eget sit amet tellus cras adipiscing enim eu turpis. Nec tincidunt praesent semper feugiat nibh sed. Sem viverra aliquet eget sit amet tellus cras. Ultricies mi quis hendrerit dolor magna. Leo integer malesuada nunc vel risus commodo. Facilisis volutpat est velit egestas dui. Quis hendrerit dolor magna eget est lorem. Proin fermentum leo vel orci porta non pulvinar neque. In vitae turpis massa sed elementum. Leo a diam sollicitudin tempor id eu. Ac auctor augue mauris augue. Ultrices dui sapien eget mi proin sed libero enim sed. Lectus proin nibh nisl condimentum id. Quis vel eros donec ac odio tempor orci dapibus. Vel risus commodo viverra maecenas accumsan. Tempor orci eu lobortis elementum nibh tellus molestie nunc. Dignissim sodales ut eu sem. Massa tincidunt dui ut ornare lectus. Lacus vel facilisis volutpat est velit egestas dui.</p>

<p>Lorem donec massa sapien faucibus et molestie ac. Pulvinar mattis nunc sed blandit libero volutpat sed. Aliquam sem et tortor consequat id. Maecenas sed enim ut sem viverra. Massa sapien faucibus et molestie ac feugiat sed lectus. Amet venenatis urna cursus eget. Quam viverra orci sagittis eu volutpat odio facilisis. Enim eu turpis egestas pretium aenean pharetra magna ac placerat. Sagittis aliquam malesuada bibendum arcu. Feugiat nisl pretium fusce id velit ut tortor pretium. Turpis nunc eget lorem dolor sed viverra ipsum. Facilisi morbi tempus iaculis urna id volutpat lacus laoreet. Malesuada bibendum arcu vitae elementum curabitur vitae nunc sed. Odio eu feugiat pretium nibh ipsum. Rhoncus est pellentesque elit ullamcorper dignissim cras tincidunt lobortis feugiat. Sapien pellentesque habitant morbi tristique senectus. Varius sit amet mattis vulputate enim nulla aliquet porttitor. Mauris in aliquam sem fringilla ut morbi tincidunt augue. Magna eget est lorem ipsum dolor sit amet consectetur adipiscing.</p>

<p>Fusce id velit ut tortor. Cras sed felis eget velit aliquet sagittis id. Elementum tempus egestas sed sed. Gravida in fermentum et sollicitudin ac. Arcu dui vivamus arcu felis bibendum ut tristique et. Ac turpis egestas integer eget aliquet nibh praesent tristique. Vulputate enim nulla aliquet porttitor. Amet luctus venenatis lectus magna. At lectus urna duis convallis convallis tellus id interdum velit. Arcu ac tortor dignissim convallis aenean et. Fermentum odio eu feugiat pretium nibh ipsum consequat. Urna duis convallis convallis tellus id. Molestie at elementum eu facilisis sed odio. Tempor orci dapibus ultrices in iaculis.</p>

<p>Mattis vulputate enim nulla aliquet porttitor. Purus sit amet volutpat consequat mauris nunc. Urna nunc id cursus metus aliquam eleifend mi. Ullamcorper velit sed ullamcorper morbi tincidunt ornare. Sodales ut eu sem integer vitae justo eget magna fermentum. Odio ut sem nulla pharetra diam sit. Malesuada bibendum arcu vitae elementum curabitur vitae nunc sed. Scelerisque felis imperdiet proin fermentum leo vel orci. Magnis dis parturient montes nascetur ridiculus. Non arcu risus quis varius quam quisque id. Ullamcorper sit amet risus nullam eget felis eget. Lacus sed viverra tellus in hac habitasse platea dictumst vestibulum. Eleifend donec pretium vulputate sapien nec sagittis aliquam. Posuere sollicitudin aliquam ultrices sagittis. Phasellus vestibulum lorem sed risus ultricies.</p>

<p>Nec tincidunt praesent semper feugiat nibh. Id interdum velit laoreet id donec ultrices tincidunt. Senectus et netus et malesuada fames ac turpis egestas maecenas. Aliquam sem et tortor consequat id porta nibh. Adipiscing elit ut aliquam purus sit. Aliquet nibh praesent tristique magna. Id velit ut tortor pretium. Quis varius quam quisque id diam. In hac habitasse platea dictumst vestibulum rhoncus est pellentesque elit. Id cursus metus aliquam eleifend mi in nulla posuere. Imperdiet proin fermentum leo vel orci porta. Lectus mauris ultrices eros in cursus turpis massa tincidunt. Ut ornare lectus sit amet. Egestas congue quisque egestas diam in arcu. Scelerisque felis imperdiet proin fermentum leo vel orci. In nulla posuere sollicitudin aliquam ultrices sagittis orci a scelerisque. A condimentum vitae sapien pellentesque. A diam maecenas sed enim ut sem viverra. Sed id semper risus in hendrerit gravida rutrum. Enim praesent elementum facilisis leo vel fringilla est ullamcorper eget.</p>', 2, 'hello notes', 1);
SET IDENTITY_INSERT [Chapter] OFF

SET IDENTITY_INSERT [StoryTag] ON
INSERT INTO [StoryTag] ([Id], [StoryId], [TagId])
VALUES (1, 1, 1), (2, 1, 50);
SET IDENTITY_INSERT [StoryTag] OFF

SET IDENTITY_INSERT [StoryGenre] ON
INSERT INTO [StoryGenre] ([Id], [StoryId], [GenreId])
VALUES (1, 1, 1), (2, 1, 12);
SET IDENTITY_INSERT [StoryGenre] OFF

SET IDENTITY_INSERT [Bookmark] ON
INSERT INTO [Bookmark] ([Id], [StoryId], [UserId], [Notes])
VALUES (1, 1, 1, NULL), (2, 1, 2, NULL);
SET IDENTITY_INSERT [Bookmark] OFF